name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      # 1. Memaksa nama di pubspec.yaml menjadi huruf kecil semua (vault_krypt)
      - name: Fix pubspec.yaml naming rule
        run: |
          sed -i 's/^name: .*/name: vault_krypt/' pubspec.yaml

      # 2. Membuat folder Android di direktori /tmp agar Flutter tidak mendeteksi nama repo VaultX
      - name: Generate Clean Android Folder
        run: |
          cd /tmp
          flutter config --no-analytics
          flutter create --platforms android --org com.elvandito --project-name vault_krypt dummy_project
          
          # Kembali ke direktori repo kita dan timpa folder android lama dengan yang baru
          cd ${{ github.workspace }}
          rm -rf android/
          cp -r /tmp/dummy_project/android ./

      # 3. Download package cryptography, dll
      - name: Install dependencies
        run: flutter pub get

      # 4. Build APK Release
      - name: Build APK
        run: flutter build apk --release

      # 5. Simpan APK ke GitHub Artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vaultkrypt-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
